"""
Builds notebooks/analysis.ipynb from scratch (as source text, not by hand in
the Jupyter UI) so the analysis is easy to review/diff, then this same
process executes it end-to-end and saves it with outputs baked in.

Run:
    python3 notebooks/build_notebook.py
"""

import nbformat as nbf
from nbclient import NotebookClient
from pathlib import Path

nb = nbf.v4.new_notebook()
cells = []


def md(text: str) -> None:
    cells.append(nbf.v4.new_markdown_cell(text))


def code(text: str) -> None:
    cells.append(nbf.v4.new_code_cell(text))


md("""\
# Retail Inventory Analytics

**Business question:** across a 6-store retail chain, where is inventory
being managed well, where is it costing us in lost sales (stockouts) or tied
up cash (slow-moving stock), and what should the ops team fix first?

**Data:** one year (FY2025) of simulated daily point-of-sale and inventory
data for 6 stores x 30 SKUs across 8 categories — ~65,700 store/product/day
records. Generated by `data/generate_data.py` with realistic seasonality,
day-of-week traffic patterns, promotions, and lead-time-based replenishment
(so stockouts and slow movers are *emergent*, not injected).

**Tools:** Python (pandas, matplotlib), SQL (see `sql/`), and a lightweight
HTML/JS dashboard (`dashboard.html`) built from this notebook's output.
""")

code("""\
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

pd.set_option("display.float_format", lambda x: f"{x:,.2f}")
plt.rcParams["figure.dpi"] = 110
plt.rcParams["axes.spines.top"] = False
plt.rcParams["axes.spines.right"] = False

stores = pd.read_csv("../data/stores.csv")
products = pd.read_csv("../data/products.csv")
txn = pd.read_csv("../data/inventory_transactions.csv", parse_dates=["date"])

df = txn.merge(products, on="product_id").merge(stores, on="store_id")
df["revenue"] = df["units_sold"] * df["unit_price"]
df["cogs"] = df["units_sold"] * df["unit_cost"]
df["month"] = df["date"].dt.to_period("M").astype(str)

print(f"{len(df):,} rows | {df['store_id'].nunique()} stores | "
      f"{df['product_id'].nunique()} products | "
      f"{df['date'].min().date()} to {df['date'].max().date()}")
df.head()
""")

md("## 1. Chain-wide KPIs")

code("""\
total_revenue = df["revenue"].sum()
total_units = df["units_sold"].sum()
total_cogs = df["cogs"].sum()
gross_margin_pct = (total_revenue - total_cogs) / total_revenue * 100
stockout_rate = df["stockout_flag"].mean() * 100
lost_units = (df["units_demanded"] - df["units_sold"]).clip(lower=0)
lost_revenue = (lost_units * df["unit_price"]).sum()

kpis = {
    "total_revenue": round(total_revenue, 2),
    "total_units_sold": int(total_units),
    "gross_margin_pct": round(gross_margin_pct, 1),
    "stockout_rate_pct": round(stockout_rate, 2),
    "estimated_lost_revenue_from_stockouts": round(lost_revenue, 2),
}
kpis
""")

md("""\
**Reading this:** a ~1-2% stockout rate sounds small, but multiplied across
65,700 store-product-days it translates into real forgone revenue — that
`estimated_lost_revenue_from_stockouts` number is what a reorder-point fix is
worth chasing.
""")

md("## 2. Monthly revenue trend")

code("""\
monthly = df.groupby("month")["revenue"].sum()

fig, ax = plt.subplots(figsize=(9, 4))
ax.plot(monthly.index, monthly.values, marker="o", color="#2563eb")
ax.set_title("Monthly Revenue — FY2025 (all stores)")
ax.set_ylabel("Revenue ($)")
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x/1000:.0f}K"))
plt.xticks(rotation=45)
ax.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.savefig("../assets/monthly_revenue.png")
plt.show()
""")

md("""\
Revenue climbs steadily through summer (beverage/produce seasonality) and
spikes sharply in November-December — the holiday bump built into the
simulation, and exactly the pattern a retail analyst would expect to see and
should staff/inventory around.
""")

md("## 3. Top products & ABC (Pareto) analysis")

code("""\
product_revenue = (
    df.groupby(["product_id", "product_name", "category"])["revenue"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

top10 = product_revenue.head(10)

fig, ax = plt.subplots(figsize=(9, 5))
ax.barh(top10["product_name"][::-1], top10["revenue"][::-1], color="#2563eb")
ax.set_title("Top 10 Products by Revenue")
ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x/1000:.0f}K"))
plt.tight_layout()
plt.savefig("../assets/top_products.png")
plt.show()

top10
""")

code("""\
pr = product_revenue.copy()
pr["cum_share"] = pr["revenue"].cumsum() / pr["revenue"].sum()
pr["abc_class"] = np.where(pr["cum_share"] <= 0.80, "A",
                     np.where(pr["cum_share"] <= 0.95, "B", "C"))

abc_summary = pr.groupby("abc_class").agg(
    products=("product_id", "count"),
    revenue=("revenue", "sum"),
).assign(revenue_share=lambda d: (d["revenue"] / d["revenue"].sum() * 100).round(1))

abc_summary
""")

md("""\
Classic 80/20 pattern: a small "A" group of SKUs (mostly beverages and a
couple of staples) drives most revenue. Those are the items where a stockout
hurts most and where inventory should be prioritized; "C" items are
candidates for reduced safety stock.
""")

md("## 4. Category & store performance")

code("""\
cat_revenue = df.groupby("category")["revenue"].sum().sort_values(ascending=False)

fig, ax = plt.subplots(figsize=(7, 7))
ax.pie(
    cat_revenue.values,
    labels=cat_revenue.index,
    autopct="%1.0f%%",
    startangle=90,
    colors=plt.cm.Blues_r(np.linspace(0.3, 0.9, len(cat_revenue))),
)
ax.set_title("Revenue Share by Category")
plt.tight_layout()
plt.savefig("../assets/category_share.png")
plt.show()
""")

code("""\
store_perf = (
    df.groupby(["store_id", "store_name", "region"])
    .agg(revenue=("revenue", "sum"), stockout_rate_pct=("stockout_flag", lambda s: s.mean() * 100))
    .reset_index()
    .sort_values("revenue", ascending=False)
)
store_perf["revenue_rank"] = store_perf["revenue"].rank(ascending=False).astype(int)
store_perf
""")

code("""\
fig, ax1 = plt.subplots(figsize=(9, 4.5))
order = store_perf.sort_values("revenue", ascending=False)
ax1.bar(order["store_name"], order["revenue"], color="#2563eb")
ax1.set_ylabel("Revenue ($)")
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x/1000:.0f}K"))
ax1.set_title("Revenue and Stockout Rate by Store")

ax2 = ax1.twinx()
ax2.plot(order["store_name"], order["stockout_rate_pct"], color="#dc2626", marker="o")
ax2.set_ylabel("Stockout rate (%)", color="#dc2626")
ax2.tick_params(axis="y", colors="#dc2626")

plt.xticks(rotation=20)
plt.tight_layout()
plt.savefig("../assets/store_performance.png")
plt.show()
""")

md("""\
Chicago Loop leads on revenue — and also has the highest stockout rate, with
every other store's stockout rate tracking its revenue rank almost exactly.
That's a real signal, not noise: reorder points in this dataset are set per
product, not per store, so a higher-traffic store burns through the same
reorder point faster and gets caught out between replenishment cycles more
often. The fix isn't more inventory everywhere — it's store-aware reorder
points (or more frequent replenishment) at the highest-volume locations.
""")

md("## 5. Inventory turnover — where is cash tied up?")

code("""\
inv = (
    df.groupby(["product_id", "product_name", "category"])
    .agg(
        annual_cogs=("cogs", "sum"),
        avg_inventory_value=("units_in_stock_eod", lambda s: (s * df.loc[s.index, "unit_cost"]).mean()),
    )
    .reset_index()
)
inv["turnover_ratio"] = inv["annual_cogs"] / inv["avg_inventory_value"]
inv_sorted = inv.sort_values("turnover_ratio")

fig, ax = plt.subplots(figsize=(9, 4))
ax.hist(inv["turnover_ratio"], bins=15, color="#2563eb", edgecolor="white")
ax.set_title("Distribution of Inventory Turnover Ratio (annualized) by SKU")
ax.set_xlabel("Turnover ratio (COGS / avg inventory value)")
plt.tight_layout()
plt.savefig("../assets/turnover_distribution.png")
plt.show()

print("Slowest-turning 5 SKUs (cash tied up relative to sales):")
inv_sorted.head(5)
""")

md("## 6. Stockout risk — where are we losing sales?")

code("""\
def _risk_metrics(g):
    return pd.Series({
        "pct_days_at_or_below_reorder_point": (g["units_in_stock_eod"] <= g["reorder_point"]).mean() * 100,
        "stockout_rate_pct": g["stockout_flag"].mean() * 100,
        "lost_revenue": ((g["units_demanded"] - g["units_sold"]).clip(lower=0) * g["unit_price"]).sum(),
    })

risk = (
    df.groupby(["product_id", "product_name"], group_keys=False)[
        ["units_in_stock_eod", "reorder_point", "stockout_flag", "units_demanded", "units_sold", "unit_price"]
    ]
    .apply(_risk_metrics)
    .reset_index()
    .sort_values("lost_revenue", ascending=False)
)
risk.head(10)
""")

md("""\
These are the SKUs to fix first: raising their reorder point (or shortening
supplier lead time) would recover the most lost revenue for the least
inventory investment — a much more targeted ask than "increase safety stock
across the board."
""")

md("## 7. Export summary for the live dashboard")

code("""\
summary = {
    "generated_from": "notebooks/analysis.ipynb",
    "kpis": kpis,
    "monthly_revenue": [
        {"month": m, "revenue": round(v, 2)} for m, v in monthly.items()
    ],
    "top_products": [
        {"name": r.product_name, "category": r.category, "revenue": round(r.revenue, 2)}
        for r in top10.itertuples()
    ],
    "category_share": [
        {"category": c, "revenue": round(v, 2)} for c, v in cat_revenue.items()
    ],
    "store_performance": [
        {
            "store_name": r.store_name,
            "region": r.region,
            "revenue": round(r.revenue, 2),
            "stockout_rate_pct": round(r.stockout_rate_pct, 2),
        }
        for r in store_perf.itertuples()
    ],
    "abc_summary": [
        {"class": idx, "products": int(row.products), "revenue": round(row.revenue, 2), "revenue_share_pct": row.revenue_share}
        for idx, row in abc_summary.iterrows()
    ],
    "top_stockout_risk": [
        {
            "name": r.product_name,
            "pct_days_at_or_below_reorder_point": round(r.pct_days_at_or_below_reorder_point, 1),
            "lost_revenue": round(r.lost_revenue, 2),
        }
        for r in risk.head(8).itertuples()
    ],
}

with open("../assets/dashboard_summary.json", "w") as f:
    json.dump(summary, f, indent=2)

print("Wrote ../assets/dashboard_summary.json")
""")

md("""\
## Key findings & recommendations

1. **Holiday demand (Nov-Dec) drives a ~30% revenue spike** over the summer
   baseline — replenishment orders for A-class SKUs should go out earlier
   (accounting for supplier lead time) to avoid stockouts during the peak.
2. **A small set of "A" products drive the majority of revenue** (80/20
   pattern) — prioritize these for safety stock and reorder-point review;
   "C" products are candidates for reduced stock to free up cash.
3. **A handful of SKUs account for most of the estimated lost revenue from
   stockouts** — fixing reorder points on just those items is a
   higher-leverage fix than a chain-wide inventory increase.
4. **Turnover ratio varies widely by SKU** — the slowest-turning products tie
   up cash disproportionately to the revenue they generate and are worth a
   markdown or reduced-order-quantity review.
5. **Stockout rate scales with store volume** because reorder points are set
   per product, not per store — the highest-revenue store (Chicago Loop) also
   has by far the highest stockout rate. Store-aware reorder points would
   likely close most of this gap.

*Next steps: bring in real POS/inventory data, validate the reorder-point
assumptions against actual supplier lead times, and track these KPIs on a
recurring (weekly) cadence rather than as a one-time analysis.*
""")

nb["cells"] = cells

notebook_path = Path("notebooks/analysis.ipynb")
notebook_path.parent.mkdir(exist_ok=True)
nbf.write(nb, notebook_path)
print(f"Wrote {notebook_path} ({len(cells)} cells, not yet executed)")

client = NotebookClient(nb, timeout=600, kernel_name="python3", resources={"metadata": {"path": "notebooks"}})
client.execute()
nbf.write(nb, notebook_path)
print(f"Executed and saved {notebook_path} with outputs")
